on:
  schedule:
    - cron: '0 9 * * *'  # daily at 9am UTC
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
        # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

        # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  
          
      - name: Install dependencies
        run: npm install
          
        #run
      - name: Scrape GH Repos
        run: |
          node scripts/gh-scraper.js
          
        #push
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.MASTER_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          git add .
          git diff --cached --quiet && echo "No changes, skipping commit." && exit 0
      
          git commit -m "chore(auto): Update JSON [CI]"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin main
