on:
  schedule:
    - cron: '0 2 * * *'  # daily at 2am UTC

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scrape GH Repos
        run: |
          node scripts/scrape-gh.js
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated Scraper Update"
          git push
