on:
  schedule:
    - cron: '0 9 * * *'  # daily at 9am UTC

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
        # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  
  
      - name: Install dependencies
        run:
          npm install
          
        #run
      - uses: actions/checkout@v3
      - name: Scrape GH Repos
        run: |
          node scripts/gh-scraper.js
          
        #push
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          git add .
          # Check if there's anything to commit
          git diff --cached --quiet && echo "No changes, skipping commit." && exit 0
      
          git commit -m "chore(auto): Update JSON [CI]"
          git push origin main
